apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: music-catalog
  name: music-catalog
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: music-catalog
  template:
    metadata:
      labels:
        app: music-catalog
    spec:
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: music-catalog
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 256Mi