apiVersion: v1
kind: Service
metadata:
  labels:
    app: music-catalog
  name: music-catalog
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: music-catalog